### ISSUE TITLE
Make a proper ramp-data repository

### ISSUE THREAD

**Issue by glemaitre** [ramp-kits/covertype#2]
I think that we should be removing the `setting_up.ipynb` notebook and make a proper `ramp-data` repository. Also, I am not sure that we have a public and private set then.

**Comment by agramfort** [comment]
data is here public coming from openml. I could replicate settting_up.ipynb
by a prepare_data.py that downloads from openml?

>

**Comment by glemaitre** [comment]
Yes and it seems that we don't have a public and private sets?

**Comment by agramfort** [comment]
true. What do you suggest for generally open data like openml?

>

**Comment by glemaitre** [comment]
that the script will call `fetch_openml` instead of `fetch_from_osf`.
`prepare_data.py` will be in charge of splitting public train/test and private train/test and we copy the data into the starting-kit.

If it is still too large for the starting-kit, then we make a downloader for a OSF project which will be opened (but I think that we should not have that much of this case, maybe the autism).

**Comment by agramfort** [comment]
I like this idea of fetch_XXX and then consistent behavior !

>
